### ISSUE TITLE
CREATE_*_NOSAVE

### ISSUE THREAD

**Issue by thelink2012** [cleolibrary/CLEO4#6] opened 2016-11-09 22:21 UTC
The following entity creation opcodes may need a NOSAVE variant, since custom scripts tend to accidentally store them in save games:
 
 + Objects
 + Blips
 + Pickups
 + Car Generators
+ 3DMarkers?

The original commands could redirect to those commands by default for custom scripts, but I don't really know if this is a very backward compatible idea.

This is a possible solution for #3

**Comment by JuniorDjjr** [comment] 2018-02-23 12:34
_"The original commands could redirect to those commands by default for custom scripts, but I don't really know if this is a very backward compatible idea."_

It is.
Usually mods tend to create and trust that their creations will never despawn.
Also, this will break various mods that use this "problem" as a benefit. So much that this is one of SAVE_THIS_CUSTOM_SCRIPT's goals.

The best solution for sure is to create a new command.

**Comment by Fabio3rs** [comment] 2018-02-24 04:26
Maybe redirect the original commands and test if a equal entity already exists to avoid duplicates.
Something like this: (pseudocode)

`foreach gen : generatorsList

if model == gen.model && pos == gen.pos
return gen.handle // return existing entity

endforeach

// create new entity
`

**Comment by x87** [comment] 2018-02-24 18:06
@Fabio3rs I like this idea

**Comment by JuniorDjjr** [comment] 2018-02-25 02:14
It's a very good ideia to avoid duplications. Except for objects.

**Comment by x87** [comment] 2018-02-26 14:43
@JuniorDjjr Why can't the same approach be used for objects in your opinion?

**Comment by JuniorDjjr** [comment] 2018-02-26 15:46
Creating same objects in the same place and then being moved seems like a common thing to do. I can't think many examples, but I imagine scripts that create several objects in the same place, all invisible or not, and then take one by one to perform some movement (like attach in a bone, make liftable). Or something related to damage, where you will break one by one, as if it were layers.

If someone has already made mods in this way, it should be few ones, so it should be feasible to just warn this for future mods.

Probably also require to test scale and rotation. Imagine a clouds mod, where the same model is created in the same place (the pivot is in the position of the player), but with another rotation and scale to vary the clouds.
Also, some extra (variation) system mod for objects (one thing I'd like to do) the same object being created with different extra mesh would also be common. However, just make it clear about the new feature for coders change coord in 0.001 to bypass.

Are small issues, it doesn't seem like much of a problem for older mods, and seem to be solved with a good education about the new feature.

**Comment by x87** [comment] 2018-02-27 13:30
Fair enough. As the duplicate problem mainly affects car generators, pickups and blips, being rarely seen for objects, we could initially make a duplicate-skip patch for those three to see how it works.

**Comment by Fabio3rs** [comment] 2018-02-28 17:57
{217446} 014B: $2770 = init_car_generator #GREENWOO color -1 -1 force_spawn 0 alarm 0 door_lock 0 min_delay 0 max_delay 10000 at 2216.902 -1160.403 24.7265 angle 270.8013 
{217489} 014B: $2771 = init_car_generator #GREENWOO color -1 -1 force_spawn 0 alarm 0 door_lock 0 min_delay 0 max_delay 10000 at 2216.902 -1160.403 24.7265 angle 270.8013 



The main.scm has two identical generators. Maybe make the code work only in custom scripts?

**Comment by x87** [comment] 2020-10-25 00:12
Looks like some of these opcoded were implemented in CLEO+. I think it's a right direction: to keep the core slim and stable and encourage for extra instructions via plugins. 

Closing?

**Comment by JuniorDjjr** [comment] 2020-10-25 01:53
Just not pickups and 3D markers (this second one I don't know if they are saved). But CLEO+ also includes save event, so you can delete all stuff before the game is saved, so, the problem is 100% solved by CLEO+ plugin.

You can close it.

**Comment by thelink2012** [comment] 2020-10-25 16:48
+1 on keeping the core slim. I think the core should provide essential functionalities as well as functionalities that would require updates on the script engine, thus avoiding multiple scripts and plugins conflicting with each other (or even with CLEO itself on update).

I think CLEO+ is a really nice idea in this direction. DK's NewOpcodes was one of these ideas too. We'll always need more commands to reduce boilerplate, and adding such a complexity to CLEO itself doesn't seem like a good decision on the compatibility and maintainability direction.

**Closed** 2020-10-26 16:01 UTC
Labels: new feature
